## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("CSEB_Attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0%,Critical,36 more,Never,12
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0

#### Section 1: Data Inspection

In [9]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------


df.head(10)
df.shape
df.dtypes

Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [11]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
df.isnull().sum()
(df["Last Present Date"] == "Never").sum()

np.int64(2)

In [13]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.columns = ['roll_no', 'student_name', 'subject', 'total_classes',
              'present', 'absent', 'excused', 'attendance_pct',
              'status', 'classes_needed_75_pct', 'last_present_date',
              'consecutive_absences']

df.columns
df

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0%,Critical,36 more,Never,12
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0

In [19]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code----------------------------
df["attendance_pct"] = pd.to_numeric(df["attendance_pct"].astype(str).str.replace("%", ""), errors="coerce")

df["last_present_date"] = pd.to_datetime(df["last_present_date"], errors="coerce")

df[["attendance_pct", "last_present_date"]].head()

   attendance_pct last_present_date
0            1.00        2026-10-09
1            1.00        2026-10-09
2            1.00        2026-10-09
3            0.92        2026-10-09
4            0.92        2026-10-09

#### Section 2: Filtering & Selection

In [20]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
df[df["status"] == "Critical"].sort_values(by="attendance_pct", ascending=True)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences
10,4MW24CS071,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12
13,4MW24CS074,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-22,4
5,4MW24CS066,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5
49,4MW24CS110,PRATHWEESH,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5
46,4MW24CS107,PRATHAM G KUMAR,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5
35,4MW24CS096,NITHIL SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5
29,4MW24CS090,NIKHIL NAIK,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-10-09,0
51,4MW24CS112,RAHUL,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-09-29,2

In [21]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
df[df["present"] == 0][["roll_no", "student_name", "consecutive_absences"]]

       roll_no     student_name  consecutive_absences
10  4MW24CS071       LAXMEESH V                    12
63  4MW25CS405  MANYA PRARTHANA                    12

In [23]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
df.loc[df["status"] == "Safe"]
df.iloc[:15, 1:6]

,student_name,subject,total_classes,present,absent
0,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
1,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
2,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
3,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1
4,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1
5,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11
6,KRITHI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
7,KRITHIKA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
8,LAKSHMI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
9,LAVANYA SHANKAR MOGER,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2
10,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12
11,LIKHITA S,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
12,LIPIKA NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1
13,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11
14,MANASA R KULAL,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0

In [24]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
df.loc[df["consecutive_absences"] >= 5, ["student_name", "status", "last_present_date"]]

       student_name    status last_present_date
5        KOUSHTUBHA  Critical        2026-09-18
10       LAXMEESH V  Critical               NaT
35    NITHIL SHETTY  Critical        2026-09-18
46  PRATHAM G KUMAR  Critical        2026-09-18
49       PRATHWEESH  Critical        2026-09-18
63  MANYA PRARTHANA  Critical               NaT

### Section 3: Grouping & Aggregation

In [25]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
)

          student_count  average_attendance  max_consecutive_absences
status
Critical              9            0.173333                        12
Safe                 42            0.969524                         0
Warning              14            0.807143                         1

In [27]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_category"] = np.where(
    df["attendance_pct"] >= 0.90, "Excellent",
    np.where(
        df["attendance_pct"] >= 0.75, "Good",
        np.where(
            df["attendance_pct"] >= 0.60, "Average", "Poor"
        )
    )
)

df.groupby("attendance_category")["student_name"].count()

attendance_category
Excellent    42
Good         14
Poor          9
Name: student_name, dtype: int64

In [28]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
df.agg({
    "total_classes": "sum",
    "present": "sum",
    "absent": "sum"
})

total_classes    780
present          643
absent           137
dtype: int64

In [29]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
df.groupby("status").agg(
    present_min=("present", "min"),
    present_max=("present", "max"),
    present_mean=("present", "mean"),
    absent_sum=("absent", "sum")
)

          present_min  present_max  present_mean  absent_sum
status
Critical            0            7      2.111111          89
Safe               11           12     11.619048          16
Warning             9           10      9.714286          32

### Section 4: Feature Engineering & Transformation

In [30]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df["risk_score"] = (df["absent"] * 0.4) + (df["consecutive_absences"] * 0.6)

df.sort_values(by="risk_score", ascending=False).head(10)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score
10,4MW24CS071,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0
46,4MW24CS107,PRATHAM G KUMAR,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,Poor,7.4
35,4MW24CS096,NITHIL SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,Poor,7.4
5,4MW24CS066,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,Poor,7.4
49,4MW24CS110,PRATHWEESH,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,Poor,7.4
13,4MW24CS074,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-22,4,Poor,6.8
51,4MW24CS112,RAHUL,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-09-29,2,Poor,3.2
29,4MW24CS090,NIKHIL NAIK,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-10-09,0,Poor,2.0
33,4MW24CS094,NISHA M B,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-06,1,Good,1.4

In [31]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
df["classes_needed_numeric"] = df["classes_needed_75_pct"].str.extract(r"(\d+)").astype(float).fillna(0)

df[["classes_needed_75_pct", "classes_needed_numeric"]].head()

  classes_needed_75_pct  classes_needed_numeric
0                 ✓ Met                     0.0
1                 ✓ Met                     0.0
2                 ✓ Met                     0.0
3                 ✓ Met                     0.0
4                 ✓ Met                     0.0

In [32]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df["attendance_flag"] = df["attendance_pct"].apply(lambda x: "Defaulter" if x < 0.75 else "Safe")

df[["attendance_pct", "attendance_flag"]].head()

   attendance_pct attendance_flag
0            1.00            Safe
1            1.00            Safe
2            1.00            Safe
3            0.92            Safe
4            0.92            Safe

In [33]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_range"] = pd.cut(
    df["attendance_pct"] * 100,
    bins=[0, 50, 75, 90, 100],
    labels=["Critical", "Warning", "Good", "Excellent"],
    include_lowest=True
)

df[["attendance_pct", "attendance_range"]].head()

   attendance_pct attendance_range
0            1.00        Excellent
1            1.00        Excellent
2            1.00        Excellent
3            0.92        Excellent
4            0.92        Excellent

### Section 5: Advanced Analysis

In [36]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
pd.pivot_table(
    df,
    index="status",
    columns="attendance_category",
    values="student_name",
    aggfunc="count",
    fill_value=0
)

attendance_category  Excellent  Good  Poor
status
Critical                     0     0     9
Safe                        42     0     0
Warning                      0    14     0

In [37]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
df["base_name"] = df["student_name"].str.split().str[0]

df[df["base_name"].duplicated(keep=False)].sort_values("base_name")

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
16,4MW24CS077,MANYA,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0.0,Safe,Excellent,MANYA
17,4MW24CS078,MANYA B C,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0.0,Safe,Excellent,MANYA
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0,36.0,Defaulter,Critical,MANYA
25,4MW24CS086,NAVYA,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Good,0.8,0.0,Safe,Good,NAVYA
26,4MW24CS087,NAVYA NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0.0,Safe,Excellent,NAVYA
32,4MW24CS093,NISHA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0.0,Safe,Excellent,NISHA
33,4MW24CS094,NISHA M B,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-06,1,Good,1.4,0.0,Safe,Good,NISHA
36,4MW24CS097,PANCHAMI NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0.0,Safe,Excellent,PANCHAMI
37,4MW24CS098,PANCHAMI V DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0.0,Safe,Excellent,PANCHAMI
44,4MW24CS105,PRANAV,Data Science & GenAI - 3nd Yr - CSE - B,12,9,3,0,0.75,Warning,✓ Met,2026-10-09,0,Good,1.2,0.0,Safe,Warning,PRANAV
45,4MW24CS106,PRANAV P K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0.0,Safe,Excellent,PRANAV
56,4MW24CS117,ROHAN MENDON,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0.0,Safe,Excellent,ROHAN
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Good,0.8,0.0,Safe,Good,ROHAN
59,4MW24CS120,SAHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0.0,Safe,Excellent,SAHANA
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Good,0.8,0.0,Safe,Good,SAHANA

In [38]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
Student_Details = pd.DataFrame({
    "Roll No": df["roll_no"],
    "Branch": ["CSE"] * len(df),
    "Semester": [5] * len(df)
})

Student_Details = Student_Details.rename(columns={"Roll No": "roll_no"})

merged_df = pd.merge(df, Student_Details, on="roll_no", how="inner")


merged_df

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name,Branch,Semester
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0.0,Safe,Excellent,KAVYA,CSE,5
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0.0,Safe,Excellent,KEERTHANA,CSE,5
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0.0,Safe,Excellent,KEERTHI.R.SHETTY,CSE,5
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0.0,Safe,Excellent,KHUSHI,CSE,5
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0.0,Safe,Excellent,KISHAN,CSE,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Good,0.8,0.0,Safe,Good,SAHANA,CSE,5
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0.0,Safe,Excellent,SAKSHI,CSE,5
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0.0,Safe,Excellent,MANISH,CSE,5
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0,36.0,Defaulter,Critical,MANYA,CSE,5
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Good,0.8,0.0,Safe,Good,ROHAN,CSE,5

In [39]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------
df[df["status"] == "Critical"].to_csv("critical_students.csv", index=False)

df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
).to_csv("status_summary.csv")

df.sort_values(by="risk_score", ascending=False).head(10).to_csv("top_10_risk_students.csv", index=False)

In [40]:
df[df["status"] == "Critical"].to_csv("critical_students.csv", index=False)

df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
).to_csv("status_summary.csv")

df.sort_values(by="risk_score", ascending=False).head(10).to_csv("top_10_risk_students.csv", index=False)

["critical_students.csv", "status_summary.csv", "top_10_risk_students.csv"]

['critical_students.csv', 'status_summary.csv', 'top_10_risk_students.csv']