## groupby merge or join

In [2]:
import pandas as pd

groupby

In [3]:
exp=pd.read_excel("subdata_pandas/expense (2).xlsx")
exp.head(5)

        Date    Category Sub-Category   Amount Payment Mode
0 2023-01-01     Grocery       Grocery      30         Cash
1 2023-01-02        Food    Restaurant     890          UPI
2 2023-01-04        Food        Zomato     257         Cash
3 2023-01-06  Essentials         Diary     120          UPI
4 2023-01-06  Essentials       Perfume    1500         Cash

In [21]:
#total expense for each category
exp.groupby("Category")["Amount"].sum()
exp.groupby("Category")["Amount"].agg(["sum"])
#complete expense summary for each category
exp.groupby("Category")["Amount"].agg(
    ['sum','count','min','max','mean']
)
#how much money u have paid by each payment mode
exp.groupby("Payment Mode")["Amount"].agg(['sum'])
#how many transactions were made using each payment mode
exp.groupby("Payment Mode")["Amount"].agg(['sum','count'])
#for each payment mode,calculate total amount spent across categories
exp.groupby(['Payment Mode','Category'])['Amount'].agg(['sum','count'])
exp.groupby(['Category','Payment Mode'])['Amount'].agg(['sum','count'])
#which categories have highest total expenses
exp.groupby('Category')['Amount'].sum().sort_values(
    ascending=False
)

Category
Bills         18724
Essentials     4485
Food           3022
Clothes        2890
Grocery        1028
Name: Amount, dtype: int64

#---------------Task-----------------------
# Create a DataFrame containing the total expense of each category.
# What is the average transaction amount for each payment mode?
# Find the highest individual transaction in each category
# Show total, average, minimum and maximum transaction amount for each payment mode.
# cross join task

Merge or join

In [4]:
customer=pd.read_csv("subdata_pandas/customer.csv")
customer
payment=pd.read_csv("subdata_pandas/payment.csv")
payment

   customerid  amount            mode paymentdate
0           1      60            Cash  2020-09-24
1          11      80            Cash  2021-03-01
2           2     500     Credit Card  2020-04-27
3           8     100            Cash  2021-01-26
4           7      20  Mobile Payment  2021-02-01
5          17     250     Credit Card  2021-04-01
6          10      70  Mobile Payment  2021-02-28

inner join

In [24]:
#inner
pd.merge(left=customer,right=payment,on='customerid',how='inner')
#left
pd.merge(left=customer,right=payment,on='customerid',how='left')
#right
pd.merge(left=customer,right=payment,on='customerid',how='right')
#cross join-task

   customerid firstname lastname address  amount            mode paymentdate
0           1      Mary    Smith   Delhi      60            Cash  2020-09-24
1          11       NaN      NaN     NaN      80            Cash  2021-03-01
2           2     Madan    Mohan  Mumbai     500     Credit Card  2020-04-27
3           8       NaN      NaN     NaN     100            Cash  2021-01-26
4           7       NaN      NaN     NaN      20  Mobile Payment  2021-02-01
5          17         R   Madhav     Goa     250     Credit Card  2021-04-01
6          10       NaN      NaN     NaN      70  Mobile Payment  2021-02-28