column transformation in pandas

In [1]:
import pandas as pd

 rows and column

In [28]:
sdata=pd.read_csv("subdata_pandas/student.csv")
sdata

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [13]:
#to select columns
sdata[['firstName','fees','age']]
#to selcet detailsofkarthik
sdata.loc[sdata.firstName=="Karthik"]
sdata.loc[sdata.fees>=29000]
#to slicing on rows
sdata.loc[1:5]
#to slice columns&rows both
sdata.iloc[:4,:3]
sdata.iloc[:1,:3]
sdata.iloc[2:7,1:4]

  firstName  lastName  age
2     Rohit  Bhandary   19
3     Nisha   D'Souza   20
4   Karthik   Poojary   22
5    Shreya    Shetty   19
6     Rohan      Naik   21

### filter

In [21]:

sdata['age']>20
sdata[sdata['age']>20]
student_age_filter=sdata[sdata['age']>20]
student_age_filter

    id firstName lastName  age  marks   fees
1  102    Ananya      Rao   21     92  30000
4  105   Karthik  Poojary   22     69  32000
6  107     Rohan     Naik   21     72  27000
8  109  Abhishek   Kotian   22     64  26000

In [26]:
sdata.where(sdata['age']>20,other="minor")
sdata.loc[(sdata['marks']>=85,"result")]="selected"
sdata.loc[(sdata['marks']<85,"result")]=" not selected"
sdata

    id firstName  lastName  age  marks   fees         result
0  101    Akshay    Shetty   20     85  25000       selected
1  102    Ananya       Rao   21     92  30000       selected
2  103     Rohit  Bhandary   19     76  28000   not selected
3  104     Nisha   D'Souza   20     88  25000       selected
4  105   Karthik   Poojary   22     69  32000   not selected
5  106    Shreya    Shetty   19     95  30000       selected
6  107     Rohan      Naik   21     72  27000   not selected
7  108   Deepika      Bhat   20     81  28000   not selected
8  109  Abhishek    Kotian   22     64  26000   not selected
9  110     Pooja       Rai   19     90  30000       selected

In [29]:
sdata["Fullname"]=sdata['firstName']+sdata["lastName"]
sdata

    id firstName  lastName  age  marks   fees        Fullname
0  101    Akshay    Shetty   20     85  25000    AkshayShetty
1  102    Ananya       Rao   21     92  30000       AnanyaRao
2  103     Rohit  Bhandary   19     76  28000   RohitBhandary
3  104     Nisha   D'Souza   20     88  25000    NishaD'Souza
4  105   Karthik   Poojary   22     69  32000  KarthikPoojary
5  106    Shreya    Shetty   19     95  30000    ShreyaShetty
6  107     Rohan      Naik   21     72  27000       RohanNaik
7  108   Deepika      Bhat   20     81  28000     DeepikaBhat
8  109  Abhishek    Kotian   22     64  26000  AbhishekKotian
9  110     Pooja       Rai   19     90  30000        PoojaRai