## dealing with duplicate values and missing data

In [31]:
import pandas as pd
import numpy as np

duplicate values

In [71]:
cdata=pd.read_csv("subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [ ]:
cdata.duplicated()#boolean
cdata[cdata.duplicated()]#non boolean
#based on
cdata[''

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN

In [17]:
cdata.duplicated()#boolean
cdata[cdata.duplicated()]#non boolean
#based on
cdata['EEID'].duplicated()#boolean
cdata[cdata['EEID'].duplicated()]
cdata.drop_duplicates()

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN

In [ ]:
#check null values
cdata.isnull()

    EEID   Name  gender  salary
0  False  False   False    True
1  False  False   False   False
2  False  False    True   False
3  False  False   False   False
4  False   True   False   False
5  False  False   False    True
6  False  False   False   False

In [61]:
edata=pd.read_csv("subdata_pandas/employee.csv")
edata

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,NaN,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
...,...,...,...,...,...,...,...,...,...,...
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

In [25]:
edata.isnull().sum()

id                      0
gender                  0
dateofbirth             1
education               0
department              0
salary                  0
starting_salary         0
job_time                0
previous_experience    25
minority                3
dtype: int64

In [30]:
cdata.isnull().sum()
cdata['salary'].isnull().sum()
#eleminate nan rows
cdata.dropna()

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [32]:
#replace nan with any value
cdata.replace(np.nan,"insufficient")

    EEID          Name        gender        salary
0  EMP01        ayushi             F  insufficient
1  EMP02         rohit             M       25000.0
2  EMP03      pranjali  insufficient       27000.0
3  EMP01        ayushi             F       20000.0
4  EMP05  insufficient             M       25000.0
5  EMP06         rohit             M  insufficient
6  EMP02         rohit             M       25000.0

In [73]:
#replace nan with 37000 in 7th data
# cdata['salary']=cdata['salary'].replace(np.nan,3500)
# cdata
#replcae nan salary with avg
mean=np.mean(cdata['salary'])
mean


#M2
cdata['salary']=cdata['salary'].fillna(mean)
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0

In [78]:
#forward fill (prev row)
cdata.ffill()

#backward fill(next row)
#cdata.bfill()
cdata['salary']=cdata['salary'].bfill()
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0